"use client";
import localFont from "next/font/local";
import "./css/globals.css";
import Header from "./_components/layouts/Header";
import Footer from "./_components/layouts/Footer";
import { AuthContext } from "./contexts/AuthContext";
import { useState } from "react";
import { isRestaurantAuth } from "./helpers/helper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [auth, setAuth] = useState(isRestaurantAuth());
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext.Provider value={{auth, setAuth}}>
          <Header />
            {children}
          <Footer />
        </AuthContext.Provider>
      </body>
    </html>
  );
}
