import localFont from "next/font/local";
import "./css/globals.css";
import Header from "./_components/layouts/Header";
import Footer from "./_components/layouts/Footer";
import AuthContextProvider from "./contexts/AuthContext";
import CartContextProvider from "./contexts/CartContext";
import UserAuthContextProvider from "./contexts/UserAuthContext";
import DeliveryAuthContextProvider from "./contexts/DeliveryAuthContext";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider>
          <UserAuthContextProvider>
            <AuthContextProvider>
              <DeliveryAuthContextProvider>
                <Header />
                {children}
                <Footer />
              </DeliveryAuthContextProvider>
            </AuthContextProvider>
          </UserAuthContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
